union (
    Resources
    | where type in~ (
        'microsoft.desktopvirtualization/workspaces',
        'microsoft.desktopvirtualization/hostpools',
        'microsoft.desktopvirtualization/applicationgroups',
        'microsoft.desktopvirtualization/scalingplans'
    )
), (
    DesktopVirtualizationResources
    | where type =~ 'microsoft.desktopvirtualization/hostpools/sessionhosts'
)
| project
    id,
    name,
    type,
    resourceGroup,
    subscriptionId,
    location,
    tags,
    workspaceFriendlyName = tostring(properties.friendlyName),
    workspacePublicNetworkAccess = tostring(properties.publicNetworkAccess),
    workspaceApplicationGroupReferences = properties.applicationGroupReferences,
    hostPoolFriendlyName = tostring(properties.friendlyName),
    hostPoolType = tostring(properties.hostPoolType),
    hostPoolLoadBalancerType = tostring(properties.loadBalancerType),
    hostPoolMaxSessionLimit = properties.maxSessionLimit,
    hostPoolPersonalDesktopAssignmentType = tostring(properties.personalDesktopAssignmentType),
    hostPoolPreferredAppGroupType = tostring(properties.preferredAppGroupType),
    hostPoolPublicNetworkAccess = tostring(properties.publicNetworkAccess),
    hostPoolStartVmOnConnect = properties.startVMOnConnect,
    hostPoolValidationEnvironment = properties.validationEnvironment,
    hostPoolManagementType = tostring(properties.managementType),
    hostPoolDirectUdp = tostring(properties.directUDP),
    hostPoolManagedPrivateUdp = tostring(properties.managedPrivateUDP),
    hostPoolPublicUdp = tostring(properties.publicUDP),
    hostPoolRelayUdp = tostring(properties.relayUDP),
    hostPoolAgentUpdate = properties.agentUpdate,
    applicationGroupFriendlyName = tostring(properties.friendlyName),
    applicationGroupType = tostring(properties.applicationGroupType),
    applicationGroupHostPoolArmPath = tostring(properties.hostPoolArmPath),
    applicationGroupShowInFeed = properties.showInFeed,
    sessionHostFriendlyName = tostring(properties.friendlyName),
    sessionHostLastHeartBeat = tostring(properties.lastHeartBeat),
    sessionHostSessions = properties.sessions,
    sessionHostActiveSessions = properties.activeSessions,
    sessionHostDisconnectedSessions = properties.disconnectedSessions,
    sessionHostPendingSessions = properties.pendingSessions,
    sessionHostAgentVersion = tostring(properties.agentVersion),
    sessionHostAllowNewSession = properties.allowNewSession,
    sessionHostStatus = tostring(properties.status),
    sessionHostStatusTimestamp = tostring(properties.statusTimestamp),
    sessionHostOsVersion = tostring(properties.osVersion),
    sessionHostSxsStackVersion = tostring(properties.sxSStackVersion),
    sessionHostUpdateState = tostring(properties.updateState),
    sessionHostLastUpdateTime = tostring(properties.lastUpdateTime),
    sessionHostVirtualMachineResourceId = tostring(properties.resourceId),
    scalingPlanFriendlyName = tostring(properties.friendlyName),
    scalingPlanExclusionTag = tostring(properties.exclusionTag),
    scalingPlanHostPoolType = tostring(properties.hostPoolType),
    scalingPlanTimeZone = tostring(properties.timeZone),
    scalingPlanHostPoolReferences = properties.hostPoolReferences,
    scalingPlanSchedules = properties.schedules
| order by subscriptionId asc, type asc, resourceGroup asc, name asc, id asc