DesktopVirtualizationResources
| where type =~ 'microsoft.desktopvirtualization/hostpools/sessionhosts'
| project
    id,
    name,
    type,
    resourceGroup,
    subscriptionId,
    location,
    tags,
    sessionHostFriendlyName = tostring(properties.friendlyName),
    sessionHostLastHeartBeat = format_datetime(todatetime(properties.lastHeartBeat), "yyyy-MM-dd'T'HH:mm:ss.fffffff'Z'"),
    sessionHostSessions = properties.sessions,
    sessionHostActiveSessions = properties.activeSessions,
    sessionHostDisconnectedSessions = properties.disconnectedSessions,
    sessionHostPendingSessions = properties.pendingSessions,
    sessionHostAgentVersion = tostring(properties.agentVersion),
    sessionHostAllowNewSession = properties.allowNewSession,
    sessionHostStatus = tostring(properties.status),
    sessionHostStatusTimestamp = format_datetime(todatetime(properties.statusTimestamp), "yyyy-MM-dd'T'HH:mm:ss.fffffff'Z'"),
    sessionHostOsVersion = tostring(properties.osVersion),
    sessionHostSxsStackVersion = tostring(properties.sxSStackVersion),
    sessionHostUpdateState = tostring(properties.updateState),
    sessionHostLastUpdateTime = format_datetime(todatetime(properties.lastUpdateTime), "yyyy-MM-dd'T'HH:mm:ss.fffffff'Z'"),
    sessionHostVirtualMachineResourceId = tostring(properties.resourceId)
| order by subscriptionId asc, resourceGroup asc, name asc, id asc